// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaxxxqtusS-k0MxxxxxxxxunF0M74',
    appId: '1:9xxxxxx122:web:3842f5xxxxxxxxab',
    messagingSenderId: '950xxxxxxxx22',
    projectId: 'wxxxxxxxxs-xxxxxxxx66',
    authDomain: 'witxxxxxxxxc66.firebaseapp.com',
    storageBucket: 'wixxxxxxxxxxxxxxxx6.apxxxxxxxxot.com',
    measurementId: 'G-WPxxxxxxxx6FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaxxxxxxxx62hpFsB-dLjxxxxxxxxnwk',
    appId: '1:95xxxxxxxx323122:android:5b72xxxxxxxxb81b8ab',
    messagingSenderId: '95xxxxxxxx122',
    projectId: 'witxxxxxxxx66',
    storageBucket: 'withusxxxxxxxxppspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHVG3azKFxxxxxxxxupoM0IR6J4',
    appId: '1:95xxxxxxxx3122:ios:8662xxxxxxxxa81b8ab',
    messagingSenderId: '95xxxxxxxx3122',
    projectId: 'wixxxxxxxx66',
    storageBucket: 'withusxxxxxxxxot.com',
    iosBundleId: 'com.example.withUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxxxxxxxxoM0IR6J4',
    appId: '1:9xxxxxxxx3122:ios:b2xxxxxxxx75a781b8ab',
    messagingSenderId: '95xxxxxxxx122',
    projectId: 'xxxxxxxxc66',
    storageBucket: 'withxxxxxxxxcom',
    iosBundleId: 'com.example.withUs.RunnerTests',
  );
}
