// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqtusS-k0MahwNR0WlYWUslzZ7unF0M74',
    appId: '1:950734323122:web:3842f5ecd2f1f9a881b8ab',
    messagingSenderId: '950734323122',
    projectId: 'withus-1cc66',
    authDomain: 'withus-1cc66.firebaseapp.com',
    storageBucket: 'withus-1cc66.appspot.com',
    measurementId: 'G-WPYJJKQ6FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpG8jt4SilTvPj62hpFsB-dLj076qJnwk',
    appId: '1:950734323122:android:5b72604ca225d2eb81b8ab',
    messagingSenderId: '950734323122',
    projectId: 'withus-1cc66',
    storageBucket: 'withus-1cc66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHVG3azKFFXIpJyQAEoAyBupoM0IR6J4',
    appId: '1:950734323122:ios:8662a22fff73a9aa81b8ab',
    messagingSenderId: '950734323122',
    projectId: 'withus-1cc66',
    storageBucket: 'withus-1cc66.appspot.com',
    iosBundleId: 'com.example.withUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHVG3azKFFXIpJyQAEoAyBupoM0IR6J4',
    appId: '1:950734323122:ios:b25c6e84783975a781b8ab',
    messagingSenderId: '950734323122',
    projectId: 'withus-1cc66',
    storageBucket: 'withus-1cc66.appspot.com',
    iosBundleId: 'com.example.withUs.RunnerTests',
  );
}
